# DATABASE
spring.datasource.url: jdbc:mysql://localhost:3306/nfwDB?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
spring.datasource.username: nfwUser_7
spring.datasource.password: 89_Bnhjk
spring.jpa.database: mysql

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.open-in-view: true